# Generated by Django 6.1.1 on 2026-09-24 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Lucide icon name", max_length=50
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Amenities",
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_number", models.CharField(max_length=10, unique=True)),
                ("floor", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CLEAN", "Clean"),
                            ("DIRTY", "Dirty"),
                            ("INSPECTION_REQUIRED", "Inspection Required"),
                            ("OUT_OF_SERVICE", "Out of Service / OOO"),
                        ],
                        default="CLEAN",
                        max_length=25,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "assigned_cleaner",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "HOUSEKEEPING"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_rooms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MaintenanceTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("IN_PROGRESS", "In Progress"),
                            ("RESOLVED", "Resolved"),
                        ],
                        default="OPEN",
                        max_length=15,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="maintenance_photos/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_tickets",
                        to="rooms.room",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoomCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField()),
                (
                    "base_price_npr",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price in Nepalese Rupees",
                        max_digits=10,
                    ),
                ),
                (
                    "base_price_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Price in USD",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("max_occupancy", models.PositiveIntegerField(default=2)),
                (
                    "bed_type",
                    models.CharField(
                        choices=[
                            ("SINGLE", "Single Bed"),
                            ("DOUBLE", "Double Bed"),
                            ("QUEEN", "Queen Bed"),
                            ("KING", "King Bed"),
                            ("TWIN", "Twin Beds"),
                        ],
                        default="QUEEN",
                        max_length=20,
                    ),
                ),
                (
                    "view_type",
                    models.CharField(
                        choices=[
                            ("CITY", "City View"),
                            ("HILLS", "Dharan Hills / Mountain View"),
                            ("GARDEN", "Garden View"),
                            ("COURTYARD", "Courtyard View"),
                        ],
                        default="HILLS",
                        max_length=20,
                    ),
                ),
                ("room_size_sqft", models.PositiveIntegerField(default=250)),
                ("virtual_tour_url", models.URLField(blank=True, null=True)),
                (
                    "floor_plan_image",
                    models.ImageField(blank=True, null=True, upload_to="floor_plans/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amenities",
                    models.ManyToManyField(
                        blank=True, related_name="categories", to="rooms.amenity"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Room Categories",
            },
        ),
        migrations.AddField(
            model_name="room",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rooms",
                to="rooms.roomcategory",
            ),
        ),
    ]
