# Generated by Django 6.1.1 on 2026-09-24 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gateway",
                    models.CharField(
                        choices=[
                            ("ESEWA", "eSewa (ePay v2)"),
                            ("KHALTI", "Khalti"),
                            ("FONEPAY", "Fonepay QR / ConnectIPS"),
                            ("STRIPE", "Stripe / International Cards"),
                            ("CASH", "Cash / Pay on Arrival"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount_npr", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "amount_usd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INITIATED", "Initiated"),
                            ("SUCCESS", "Success / Paid"),
                            ("FAILED", "Failed"),
                            ("REFUNDED", "Refunded"),
                        ],
                        default="INITIATED",
                        max_length=20,
                    ),
                ),
                ("transaction_uuid", models.CharField(max_length=100, unique=True)),
                (
                    "gateway_reference_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "payment_slip",
                    models.FileField(blank=True, null=True, upload_to="payment_slips/"),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="reservations.reservation",
                    ),
                ),
            ],
        ),
    ]
